### ISSUE TITLE
Activity class

### ISSUE THREAD

**Issue by DrewBradley** [dietza/FitLit#7]
As a developer,

When I have related information about users' activity,

I want to create an Activity class,

So that relevant data for different users can be accessed and used consistently.

Instantiated with one argument:
- [x] activity data object

Activity properties:
- [x] id (num)
- [x] date (*formatted string)
- [x] numSteps (num)
- [x] minutesActive (num)
- [x] flightsOfStairs (num)

Activity methods:
- [x] calculateMiles() will calculate the number of miles moved base on the number of steps and strideLength
- [x] returnDailyActiveMinutes(date) will return number of minutes active on a given date.
- [x] calculateWeeklyAverageActiveMinutes() calculate the average number of active minutes given a week.
- [x] calculateStepGoalSuccess(date) calculate whether or not the user achieved their step goal given user's goal, steps achieved, date.
- [x] returnSuccessFullStepDates() return an array of successful step goal days.
- [x] findStairclimbingRecord() return the greatest number of flights of stairs climbed in one day.
Activity methods for ALL users:
- [x] calculateAverageStairs(date) calculate the average number of stairs climbed by all users on a given date.
- [x] calculateAverageSteps(date) calculate the average number of steps taken by all users given a specific date.
- [x] calculateAverageActivity(date) calculate the average number of active minutes for all users on a specific date.

**Comment by dietza** [comment]
Made the last three methods listed here into a single dynamic method by passing in the name of the dataMetric we want to caluculate

**Comment by hfaerber** [comment]
Great work @DrewBradley  and @dietza!

This user story is laid out in a really clear and detailed way to help you as developers built out this work.  For your time at Turing I think that is a great way to set these up!  

On the job I've seen user stories written in a few different ways.   Often, they will be written from the end user's perspective rather than the developers.  A story like this one may also be broken out into several stories.    I'm sharing this you just to give insight to the working world that I didn't get to see while at Turing, not to indicate you should do anything differently when setting up your stories :)

Examples -  
1. As a FitLit user, I want to be able to see the number of miles I moved based on my numbers and stride length.
2. As a Fitlit user, I want to be able to enter a specific date and see my stats for that date including:
    - the number of minutes I was active
    - whether I met my step goal
3. As a Fitlit user, I want to be able to enter a specific date and see averages across all users on that date including:
    - average stairs
    - average steps
    - average number of active minutes
